'use strict';
// No analytics, CDN, remote provider access or browser credential persistence.
const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list = s => [...new Set(String(s || '').split(',').map(x => x.trim()).filter(Boolean))];
const clone = o => JSON.parse(JSON.stringify(o));
const badge = (s, cls = '') => `<span class="badge ${cls}">${esc(s)}</span>`;
const tags = xs => `<div class="tags">${(xs || []).map(x => badge(x)).join('')}</div>`;
let token = '', config = null, revision = '', dirty = false, tab = 'models', edit = null;
let query = '', source = '', creator = '', family = '';
const pages = {
  models: ['MODEL REGISTRY', 'Un catalogue, plusieurs sources.', 'Classez vos modèles. Décidez exactement ce que chaque clé peut voir.', '+ Ajouter un modèle', 'Modèles'],
  groups: ['ACCESS GROUPS', 'Composez vos groupes.', 'Sélection explicite ou filtres dynamiques. Les exclusions sont toujours prioritaires.', '+ Créer un groupe', 'Groupes'],
  keys: ['VIRTUAL KEY POLICIES', 'À chaque clé, sa vue.', 'Associez des groupes, choisissez un format de nom et arbitrez les collisions.', '+ Associer une clé', 'Clés virtuelles'],
  deploy: ['NATIVE BIFROST', 'Du registre au routage natif.', 'Exportez les alias et les permissions à appliquer dans votre Bifrost existant.', '', 'Déploiement'],
  settings: ['PLUGIN SETTINGS', 'Un registre, des règles explicites.', 'Configuration locale, imports et format par défaut. Aucun secret fournisseur ici.', '', 'Réglages']
};
async function api(path, method = 'GET', body, match) {
  const headers = {'Authorization': `Bearer ${token}`};
  if (body !== undefined) headers['Content-Type'] = 'application/json';
  if (match) headers['If-Match'] = `"${match}"`;
  let res;
  try {
    res = await fetch(`/api/${path}`, {method, headers, body:body === undefined ? undefined : JSON.stringify(body), cache:'no-store', credentials:'omit'});
  } catch (netErr) {
    throw new Error('réseau: ' + (netErr && netErr.message ? netErr.message : String(netErr)));
  }
  const raw = await res.text();
  let data = null;
  try { data = raw ? JSON.parse(raw) : null; } catch { throw new Error(`HTTP ${res.status}, corps non JSON: ${raw.slice(0, 120)}`); }
  if (!res.ok) throw new Error((data && data.error) ? `${data.error} (HTTP ${res.status})` : `Erreur HTTP ${res.status}`);
  return {data, revision: (res.headers.get('ETag') || '').replace(/"/g, '')};
}
function errText(err) {
  const name = err && err.name ? err.name : 'Erreur';
  const msg = err && err.message ? err.message : String(err);
  return `${name} : ${msg}`;
}
function notice(message, kind = 'success') { const el = $('#notice'); el.textContent = message; el.className = `notice ${kind}`; el.hidden = false; }
function markDirty() { dirty = true; $('#save').disabled = false; $('#save-state').textContent = 'Brouillon'; $('#save-state').className = 'badge warn'; }
function markSaved() { dirty = false; $('#save').disabled = true; $('#save-state').textContent = 'Enregistré'; $('#save-state').className = 'badge good'; $('#revision').textContent = revision.slice(0,12); }
function activeModels() { return config.models.filter(m => m.enabled && m.verified); }
function empty(symbol, title, text, buttons='') { return `<div class="empty"><div class="empty-symbol">${symbol}</div><h2>${esc(title)}</h2><p>${esc(text)}</p>${buttons}</div>`; }
function options(xs, value, all) { return `${all ? `<option value="">${esc(all)}</option>` : ''}${xs.map(x => `<option value="${esc(x)}" ${x === value ? 'selected':''}>${esc(x)}</option>`).join('')}`; }
function unique(field) { return [...new Set(config.models.map(m => m[field]).filter(Boolean))].sort(); }
function rerender() {
  const p = pages[tab]; $('#kicker').textContent=p[0]; $('#page-title').textContent=p[1]; $('#subtitle').textContent=p[2]; $('#add').textContent=p[3]; $('#add').hidden=!p[3]; $('#crumb').textContent=p[4];
  document.querySelectorAll('[data-tab]').forEach(b => b.classList.toggle('active',b.dataset.tab===tab)); $('#nav-count').textContent=config.models.length;
  ({models:renderModels,groups:renderGroups,keys:renderKeys,deploy:renderDeploy,settings:renderSettings}[tab])();
}
function renderModels() {
  const stats = [ ['Modèles enregistrés', config.models.length, 'Toutes les sources réunies', '▦'], ['Sources', unique('provider').length, 'Providers Bifrost existants', '↗'], ['Groupes', config.groups.length, 'Sélections & filtres', '◇'], ['Modèles publiables', activeModels().length, 'Actifs et déclarés vérifiés', '✓'] ];
  $('#page').innerHTML = `<div class="stats">${stats.map(([l,v,n,i]) => `<div class="stat"><div class="stat-label"><span>${l}</span><span>${i}</span></div><div class="stat-value">${v}</div><p class="fine">${n}</p></div>`).join('')}</div><section class="panel"><div class="panel-heading"><div><h3>Catalogue de modèles ${badge(config.models.length)}</h3><p>Un alias lisible. Un modèle amont. Une source explicite.</p></div><button class="secondary" data-action="import">Importer JSON</button></div><div class="toolbar"><input class="search" id="search" aria-label="Rechercher un modèle" placeholder="⌕  Rechercher un modèle, un alias…" value="${esc(query)}"><select id="filter-source" aria-label="Filtrer par source">${options(unique('provider'),source,'Toutes les sources')}</select><select id="filter-creator" aria-label="Filtrer par créateur">${options(unique('creator'),creator,'Tous les créateurs')}</select><select id="filter-family" aria-label="Filtrer par famille">${options(unique('family'),family,'Toutes les familles')}</select></div><div id="models-body"></div></section><div class="callout"><b>↳</b><div><strong>La visibilité n’est pas une preuve d’accès amont.</strong><br>Le plugin n’expose que l’intersection du registre et de la liste autorisée par Bifrost. Un modèle non vérifié reste masqué.</div></div>`;
  $('#search').addEventListener('input',e => { query=e.target.value; renderModelRows(); });
  for (const [id,key] of [['filter-source','source'],['filter-creator','creator'],['filter-family','family']]) $('#'+id).addEventListener('change',e => { if(key==='source') source=e.target.value; else if(key==='creator') creator=e.target.value; else family=e.target.value; renderModelRows(); });
  renderModelRows();
}
function renderModelRows() {
  const rows=config.models.filter(m => (!query || [m.id,m.alias,m.upstream_model,m.provider,m.creator,m.family].join(' ').toLowerCase().includes(query.toLowerCase())) && (!source || source===m.provider) && (!creator || creator===m.creator) && (!family || family===m.family));
  if (!rows.length) { $('#models-body').innerHTML = empty('▦',config.models.length?'Aucun résultat':'Votre registre commence ici.',config.models.length?'Modifiez votre recherche ou vos filtres.':'Ajoutez les identifiants de vos providers et clés existants. Le catalogue reste vide tant que vous ne publiez pas de modèles.',config.models.length?'':'<button class="primary" data-action="add">+ Ajouter un modèle</button>'); return; }
  $('#models-body').innerHTML = `<div class="table-scroll"><table><thead><tr><th>Modèle / alias</th><th>Source</th><th>Famille</th><th>Capacités</th><th>Publication</th><th></th></tr></thead><tbody>${rows.map(m => `<tr><td><div class="model-cell"><span class="model-icon">${esc((m.creator || m.provider).slice(0,2).toUpperCase())}</span><div><strong>${esc(m.alias)}</strong><span class="fine">${esc(m.creator || 'Créateur non renseigné')}</span></div></div></td><td>${badge(m.provider)}</td><td>${esc(m.family || '—')}</td><td>${tags((m.capabilities || []).slice(0,3))}</td><td>${badge(!m.enabled?'Désactivé':m.verified?'Publiable':'À vérifier',!m.enabled?'':m.verified?'good':'warn')}</td><td><div class="row-actions"><button class="quiet" data-action="edit" data-kind="models" data-id="${esc(m.id)}">Modifier</button><button class="quiet delete" data-action="delete" data-kind="models" data-id="${esc(m.id)}" aria-label="Supprimer ${esc(m.alias)}">×</button></div></td></tr>`).join('')}</tbody></table></div><div class="table-foot"><span>${rows.length} modèle(s) affiché(s)</span><span>Métadonnées riches réservées à ce panneau</span></div>`;
}
function renderGroups() {
  if (!config.groups.length) { $('#page').innerHTML=`<section class="panel">${empty('◇','Définissez un premier groupe.','Un groupe peut contenir des modèles précis, des filtres dynamiques, ou les deux. Il n’accorde aucun accès avant son association à une clé.','<button class="primary" data-action="add">+ Créer un groupe</button>')}</section>`; return; }
  $('#page').innerHTML=`<div class="cards">${config.groups.map(g => `<article class="card"><div class="card-header"><h3>${esc(g.name)}</h3>${badge(g.id,'accent')}</div><p>${g.model_ids.length} modèle(s) explicite(s)${g.filter?' · filtre dynamique':''}${g.exclude?.length?` · ${g.exclude.length} exclusion(s)`:''}</p>${tags(g.model_ids)}${g.filter?`<p class="fine">${esc(Object.entries(g.filter).map(([k,v])=>k+': '+v.join(', ')).join(' · '))}</p>`:''}<div class="row-actions"><button class="secondary" data-action="edit" data-kind="groups" data-id="${esc(g.id)}">Modifier</button><button class="quiet delete" data-action="delete" data-kind="groups" data-id="${esc(g.id)}">Supprimer</button></div></article>`).join('')}</div><div class="callout"><b>∩</b><div><strong>Filtres prévisibles.</strong><br>OU au sein des sources, créateurs et familles ; ET entre ces catégories. Toutes les capacités demandées doivent être présentes. Les exclusions sont appliquées en dernier.</div></div>`;
}
function renderKeys() {
  if (!config.policies.length) { $('#page').innerHTML=`<section class="panel">${empty('⚿','Associez une clé Bifrost existante.','Le registre lie une empreinte SHA-256 à son identifiant natif. Bifrost reste responsable de l’authentification, des budgets et des permissions.','<button class="primary" data-action="add">+ Associer une clé</button>')}</section>`; return; }
  $('#page').innerHTML=`<section class="panel">${config.policies.map(p => `<div class="key-row"><div><h3>${esc(p.name)} ${badge(p.enabled?'Active':'Désactivée',p.enabled?'good':'')}</h3><p><code>${esc(p.virtual_key_id)}</code> · Format : <code>${esc(p.naming || config.default_naming)}</code></p>${tags(p.groups)}</div><div class="row-actions"><button class="secondary" data-action="preview" data-id="${esc(p.virtual_key_id)}">Aperçu /models</button><button class="quiet" data-action="edit" data-kind="policies" data-id="${esc(p.virtual_key_id)}">Modifier</button><button class="quiet delete" data-action="delete" data-kind="policies" data-id="${esc(p.virtual_key_id)}">×</button></div></div>`).join('')}</section><div class="callout"><b>!</b><div><strong>Une sélection vide interdit tout.</strong><br>Les groupes du registre ne remplacent pas les restrictions natives de la clé. Le plan de déploiement indique les deux configurations à rapprocher.</div></div>`;
}
function renderDeploy() {
  $('#page').innerHTML=`<section class="panel"><div class="panel-heading"><div><h3>Déploiement explicite</h3><p>Le registre n’écrit pas automatiquement dans l’administration Bifrost.</p></div>${badge('Application manuelle','warn')}</div><div class="steps"><div class="step"><span class="step-number">1</span><div><h3>Vérifier le registre</h3><p>Vérifie les références, les collisions, les formats et les règles. Ne teste ni les abonnements ni les modèles amont.</p><button class="secondary" data-action="validate">Vérifier le brouillon</button></div></div><div class="step"><span class="step-number">2</span><div><h3>Exporter les primitives natives</h3><p>Alias par clé provider, cibles canoniques et permissions attendues par clé virtuelle. Le fichier est un plan, pas un corps de requête API.</p><button class="primary" data-action="plan">Voir & exporter le plan</button></div></div><div class="step"><span class="step-number">3</span><div><h3>Fusionner les alias dans une copie</h3><p>La commande préserve les credentials et les budgets. Elle refuse les conflits et n’écrase pas le fichier source. Les permissions de clés virtuelles restent à appliquer séparément.</p><pre>registry merge-aliases --config registry.json \
  --bifrost-config config.json --out config.registry.json</pre></div></div><div class="step"><span class="step-number">4</span><div><h3>Construire et charger le plugin</h3><p>Utilisez le script de build commun fourni avec le code : même checkout, même Go et mêmes dépendances pour Bifrost et le .so. Chargez le plugin en pre_builtin, puis lancez les tests live fournis.</p><pre>scripts/build-with-bifrost.sh /chemin/vers/bifrost ./dist/native</pre></div></div></div><div class="flow"><code>Client</code> → <code>Garde Registry</code> → <code>Gouvernance Bifrost</code> → <code>Alias natif</code> → <code>Provider</code></div></section><div class="callout"><b>i</b><div><strong>Ce panneau n’atteste pas le chargement du .so.</strong><br>Le build natif et la validation sur votre instance sont des étapes distinctes. L’interface est un panneau local séparé, pas un onglet ajouté au dashboard Bifrost.</div></div>`;
}
function renderSettings() {
  $('#page').innerHTML=`<div class="settings-grid"><article class="card"><h3>Format par défaut</h3><p>Appliqué aux clés qui n’ont pas défini leur propre format.</p><select id="default-naming" aria-label="Format par défaut">${options(['model','provider/model','both'],config.default_naming)}</select><p><code>model</code> : alias seul.<br><code>provider/model</code> : source explicite.<br><code>both</code> : les deux représentations.</p><div class="callout"><div>En cas d’alias partagé, indiquez une préférence explicite pour le nom court.</div></div></article><article class="card"><h3>Configuration locale</h3><p>Schéma v${config.schema_version} · Révision <code>${esc(revision.slice(0,12))}</code></p><p>Exports sans jeton brut. Les empreintes et identifiants restent des données d’administration à protéger.</p><div class="setting-actions"><button class="secondary" data-action="export">Exporter JSON</button><button class="secondary" data-action="import">Importer JSON</button><button class="quiet" data-action="reload">Recharger le fichier</button></div></article><article class="card"><h3>Ce qui reste natif</h3><p>Authentification des clés, sélection provider, alias vers les modèles amont, budgets, facturation, réponses d’inférence et fragments de streaming.</p>${tags(['Pas de proxy supplémentaire','Pas de pricing parallèle'])}</article><article class="card"><h3>Périmètre de cette version</h3><p>Catalogue OpenAI /models et requêtes JSON configurées. Pas de multipart, WebSocket, API de fournisseur natif ou synchronisation automatique de providers.</p>${badge('Validation live requise','warn')}</article></div>`;
  $('#default-naming').addEventListener('change',e=>{config.default_naming=e.target.value;markDirty();});
}
function field(name,label,value='',hint='',type='text',full=false,required=false) { const id='f-'+name; return `<div class="field ${full?'full':''}"><label for="${id}">${esc(label)}</label>${type==='textarea'?`<textarea id="${id}" name="${name}" ${required?'required':''}>${esc(value)}</textarea>`:`<input id="${id}" name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} autocomplete="off">`}${hint?`<span class="hint">${esc(hint)}</span>`:''}</div>`; }
function selectField(name,label,values,value,allowDefault=false) { return `<div class="field"><label for="f-${name}">${esc(label)}</label><select id="f-${name}" name="${name}">${options(values,value,allowDefault?'Hériter du réglage global':null)}</select></div>`; }
function checks(name,items,selected) { return `<div class="checkboxes">${items.map(([value,label])=>`<label class="check"><input type="checkbox" name="${name}" value="${esc(value)}" ${(selected||[]).includes(value)?'checked':''}>${esc(label)}</label>`).join('')}</div>`; }
function openEditor(kind, id) {
  if (kind === 'keys') kind='policies'; const arr=config[kind]; const key=kind==='policies'?'virtual_key_id':'id'; const found=arr.find(x=>x[key]===id); edit={kind,key,id,base:found?clone(found):{}};
  const m=edit.base, titles={models:'un modèle',groups:'un groupe',policies:'une clé virtuelle'}; $('#editor-title').textContent=(found?'Modifier ':'Ajouter ')+titles[kind]; $('#editor-error').textContent='';
  let html='';
  if(kind==='models') html=field('id','Identifiant du registre',m.id,'Minuscules, chiffres, tirets ou points.','text',false,true)+field('alias','Alias visible',m.alias,'Sans slash ; unique dans cette source.','text',false,true)+field('provider','Provider Bifrost existant',m.provider,'Ex. codex, antigravity : identifiant configuré dans Bifrost.','text',false,true)+field('provider_key_ids','Identifiants des clés provider',(m.provider_key_ids||[]).join(', '),'Identifiants existants, séparés par des virgules. Jamais les secrets.','text',false,true)+field('upstream_model','Identifiant du modèle amont',m.upstream_model,'La traduction vers cet identifiant reste un alias natif.','text',true,true)+field('canonical_model','Modèle canonique / pricing',m.canonical_model,'Identifiant réel dans le catalogue de prix de votre Bifrost.')+selectField('model_family','Famille native (protocole)',['','anthropic','openai','mistral','cohere','gemini','gemma','llama','imagen','veo','nova','titan'],m.model_family||'')+field('creator','Créateur (classement)',m.creator)+field('family','Famille (classement)',m.family)+field('capabilities','Capacités',(m.capabilities||[]).join(', '),'Libellés libres, séparés par des virgules.','text',true)+`<div class="field full"><label>Endpoints autorisés</label>${checks('endpoints',['chat/completions','responses','completions','embeddings','images/generations','audio/speech'].map(x=>[x,x]),m.endpoints||['chat/completions'])}</div>`+field('evidence','Origine de la vérification',m.evidence,'URL, test reproductible ou référence d’un journal de validation. Votre déclaration, pas une vérification automatique.','textarea',true)+`<div class="field full">${checks('flags',[['enabled','Activer'],['verified','Je déclare ce modèle vérifié']],[(m.enabled??true)?'enabled':'',m.verified?'verified':''])}</div>`;
  else if(kind==='groups') html=field('id','Identifiant',m.id,'','text',false,true)+field('name','Nom du groupe',m.name,'','text',false,true)+`<div class="field full"><label>Modèles explicites</label>${checks('model_ids',config.models.map(x=>[x.id,`${x.provider}/${x.alias}`]),m.model_ids)}</div>`+field('sources','Filtre · sources',(m.filter?.sources||[]).join(', '),'Séparées par des virgules.')+field('creators','Filtre · créateurs',(m.filter?.creators||[]).join(', '))+field('families','Filtre · familles',(m.filter?.families||[]).join(', '))+field('capabilities','Filtre · capacités requises',(m.filter?.capabilities||[]).join(', '))+`<div class="field full"><label>Modèles exclus</label>${checks('exclude',config.models.map(x=>[x.id,`${x.provider}/${x.alias}`]),m.exclude)}</div>`;
  else html=field('virtual_key_id','Identifiant natif de la clé',m.virtual_key_id,'Identifiant dans Bifrost, pas le jeton sk-bf-.','text',false,true)+field('name','Nom lisible',m.name,'','text',false,true)+field('token_sha256','Empreinte SHA-256',m.token_sha256,'64 caractères hexadécimaux ; utilisez la commande registry hash.','text',true)+field('raw_token','Ou calculer depuis le jeton (facultatif)','','Haché dans cet onglet via WebCrypto, puis effacé. Le jeton brut n’est pas envoyé au panneau.','password',true)+selectField('naming','Format des noms',['model','provider/model','both'],m.naming||'',true)+field('sources','Limiter aux sources',(m.sources||[]).join(', '),'Vide = pas de filtre supplémentaire sur les sources.')+`<div class="field full"><label>Groupes autorisés — aucun groupe = aucun accès</label>${checks('groups',config.groups.map(x=>[x.id,x.name]),m.groups)}</div>`+field('prefer','Préférences pour les noms courts',JSON.stringify(m.prefer||{},null,2),'JSON : {"alias": "identifiant-du-modèle-préféré"}','textarea',true)+`<div class="field full">${checks('flags',[['enabled','Activer cette politique']],m.enabled??true?['enabled']:[])}</div>`;
  $('#editor-body').innerHTML=`<div class="form-grid">${html}</div>`; $('#editor').showModal();
}
async function submitEditor(e) {
  e.preventDefault(); const f=new FormData(e.target),v=k=>String(f.get(k)||'').trim(),xs=k=>f.getAll(k).map(String),flags=xs('flags'); const m=clone(edit.base); const kind=edit.kind;
  try {
    if(kind==='models') { Object.assign(m,{id:v('id'),alias:v('alias'),provider:v('provider'),provider_key_ids:list(v('provider_key_ids')),upstream_model:v('upstream_model'),canonical_model:v('canonical_model'),model_family:v('model_family'),creator:v('creator'),family:v('family'),capabilities:list(v('capabilities')),endpoints:xs('endpoints'),evidence:v('evidence'),enabled:flags.includes('enabled'),verified:flags.includes('verified')}); }
    else if(kind==='groups') { Object.assign(m,{id:v('id'),name:v('name'),model_ids:xs('model_ids'),exclude:xs('exclude')}); const filter={}; ['sources','creators','families','capabilities'].forEach(k=>{const a=list(v(k));if(a.length)filter[k]=a;}); if(Object.keys(filter).length) m.filter=filter; else delete m.filter; }
    else { let hash=v('token_sha256'); const raw=v('raw_token'); $('#f-raw_token').value=''; if(raw){if(!raw.startsWith('sk-bf-')||raw.length<16||/\s/.test(raw))throw new Error('Jeton Bifrost invalide.');if(!globalThis.crypto?.subtle)throw new Error('WebCrypto indisponible. Utilisez registry hash ou ouvrez via localhost / HTTPS.');hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw)))].map(b=>b.toString(16).padStart(2,'0')).join('');$('#f-token_sha256').value=hash;} Object.assign(m,{virtual_key_id:v('virtual_key_id'),name:v('name'),token_sha256:hash,naming:v('naming'),groups:xs('groups'),sources:list(v('sources')),prefer:JSON.parse(v('prefer')||'{}'),enabled:flags.includes('enabled')}); }
    const next=clone(config),arr=next[kind],idx=arr.findIndex(x=>x[edit.key]===edit.id); if(idx>=0)arr[idx]=m; else arr.push(m);
    // Validate the WHOLE draft before committing an individual editor change.
    await api('validate','POST',{config:next}); config=next; markDirty(); $('#editor').close(); rerender(); notice('Modification ajoutée au brouillon. Enregistrez pour la publier dans le registre.');
  } catch(err) { $('#editor-error').textContent=errText(err); }
}
async function validate() { await api('validate','POST',{config}); notice('Structure valide : références, collisions et règles contrôlées. Aucun test amont n’a été effectué.'); }
async function save() { const b=$('#save');b.disabled=true;try{const r=await api('config','PUT',config,revision);revision=r.data.revision;markSaved();notice('Registre enregistré atomiquement. Les alias et permissions natives restent à appliquer dans Bifrost.');}catch(e){b.disabled=!dirty;notice(e.message,'error');} }
async function preview(id) {
  const {data}=await api('preview','POST',{config,virtual_key_id:id}); $('#output-title').textContent=`Vue de ${data.policy.name}`;
  $('#output-body').innerHTML=`<p class="preview-note">Aperçu du brouillon uniquement. La liste réelle sera intersectée avec les modèles autorisés par Bifrost. Cette vue ne prouve pas un accès au provider.</p>${!data.policy.enabled?'<p class="error">Politique désactivée : aucune requête n’est acceptée.</p>':''}<div class="table-scroll"><table><thead><tr><th>Nom exposé</th><th>Route native</th><th>Modèle amont</th></tr></thead><tbody>${data.routes.map(r=>`<tr><td><code>${esc(r.exposed_id)}</code></td><td><code>${esc(r.provider+'/'+r.alias)}</code></td><td><code>${esc(r.upstream_model)}</code></td></tr>`).join('')}</tbody></table></div><p class="fine">${data.routes.length} nom(s) potentiel(s). Un catalogue vide interdit tout.</p>`; $('#output').showModal();
}
async function plan() { const {data}=await api('plan','POST',{config}); $('#output-title').textContent='Plan de primitives Bifrost'; $('#output-body').innerHTML='<p class="preview-note">Plan de déploiement, pas un config.json complet ni un corps de requête API. Aucun changement natif n’a été effectué.</p><pre id="plan-json"></pre><div class="output-actions"><button class="primary" id="download-plan">Exporter le plan JSON</button></div>';$('#plan-json').textContent=JSON.stringify(data,null,2);$('#download-plan').onclick=()=>download('bifrost-native-plan.json',data);$('#output').showModal(); }
function download(name,data){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
async function reload(){if(dirty&&!confirm('Abandonner le brouillon et recharger la version enregistrée ?'))return;const r=await api('config');config=r.data;revision=r.revision;markSaved();rerender();notice('Configuration enregistrée rechargée.');}
async function act(action,el){
  if(action==='add')return openEditor(tab==='keys'?'policies':tab);
  if(action==='edit')return openEditor(el.dataset.kind,el.dataset.id);
  if(action==='delete'){const kind=el.dataset.kind,key=kind==='policies'?'virtual_key_id':'id';if(!confirm(`Supprimer ${el.dataset.id} du brouillon ?`))return;const next=clone(config);next[kind]=next[kind].filter(x=>x[key]!==el.dataset.id);await api('validate','POST',{config:next});config=next;markDirty();rerender();return;}
  if(action==='preview')return preview(el.dataset.id);
  if(action==='validate')return validate();if(action==='plan')return plan();if(action==='reload')return reload();
  if(action==='export')return download('registry.json',config);
  if(action==='import'){$('#import-file').click();return;}
}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();token=$('#admin-token').value;$('#login-error').textContent='';try{const r=await api('config');config=r.data;revision=r.revision;$('#admin-token').value='';$('#login').hidden=true;$('#workspace').hidden=false;markSaved();rerender();}catch(err){token='';$('#login-error').textContent=errText(err);}});
$('#logout').onclick=()=>{if(dirty&&!confirm('Déconnecter et abandonner le brouillon ?'))return;token='';config=null;dirty=false;$('#workspace').hidden=true;$('#login').hidden=false;$('#page').replaceChildren();$('#editor-body').replaceChildren();$('#output-body').replaceChildren();$('#notice').hidden=true;};
$('#theme-toggle').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';};
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;rerender();}));
$('#add').onclick=()=>openEditor(tab==='keys'?'policies':tab);
$('#save').onclick=save;$('#validate').onclick=()=>validate().catch(e=>notice(e.message,'error'));
$('#page').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)Promise.resolve(act(b.dataset.action,b)).catch(err=>notice(errText(err),'error'));});
$('#editor-form').addEventListener('submit',submitEditor);
for(const id of ['close-editor','cancel-editor'])$('#'+id).onclick=()=>$('#editor').close();
$('#editor').addEventListener('close',()=>{$('#editor-body').replaceChildren();edit=null;});
$('#close-output').onclick=()=>$('#output').close();
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>4*1024*1024)throw new Error('Le fichier dépasse 4 Mio.');if(dirty&&!confirm('Remplacer le brouillon actuel par ce fichier ?'))return;const raw=await file.text(); // Validate original text server-side first so duplicate JSON keys cannot be normalized away.
const res=await fetch('/api/validate',{method:'POST',headers:{'Authorization':`Bearer ${token}`,'Content-Type':'application/json'},credentials:'omit',body:'{"config":'+raw+'}'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Configuration invalide');config=JSON.parse(raw);config.models??=[];config.groups??=[];config.policies??=[];config.groups.forEach(g=>g.model_ids??=[]);config.policies.forEach(p=>p.groups??=[]);markDirty();rerender();notice('Import ajouté au brouillon. Vérifiez puis enregistrez.');}catch(err){notice(err.message,'error');}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
