import { applyKeyAdoption, clearAdminToken, getWorkspace, previewKeyAdoption, putWorkspace, readbackKey, setAdminToken } from "./api";
import { createCatalogReference, getCatalog, matchCatalogReference, overrideCatalogField, parseCatalogValue, refreshCatalog } from "./catalog-api";
import { applySnapshot, getSnapshot, getSnapshotCsv, previewSnapshot } from "./snapshot-api";
import type { Demo } from "./demo";
import { revealKeySecret } from "./key-secret-api";

const calls: { url: string; init: RequestInit }[] = [];
const equal = (actual: unknown, expected: unknown) => { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(`Expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`); };
globalThis.fetch = (async (url: string, init: RequestInit) => {
  calls.push({ url, init });
  return new Response(JSON.stringify({ revision: "next" }), { status: 200, headers: { "Content-Type": "application/json" } });
}) as typeof fetch;

const data: Demo = { models: [], groups: [], keys: [], campaigns: [] };
await getWorkspace();
setAdminToken("test-admin-token");
await putWorkspace(data, "current");
await readbackKey("native/key");
clearAdminToken();
await getWorkspace();
equal(calls[0].url, "./api/workspace");
equal(new Headers(calls[0].init.headers).has("Authorization"), false);
equal(new Headers(calls[1].init.headers).get("Authorization"), "Bearer test-admin-token");
equal(new Headers(calls[1].init.headers).get("If-Match"), "current");
equal(JSON.parse(calls[1].init.body as string), { data });
equal(calls[2].url, "./api/keys/native%2Fkey/readback");
equal(new Headers(calls[2].init.headers).get("Authorization"), "Bearer test-admin-token");
equal(new Headers(calls[3].init.headers).has("Authorization"), false);
setAdminToken("test-admin-token");
await getCatalog();
await refreshCatalog("catalog-1", ["models.dev"]);
await overrideCatalogField("catalog-2", "reference", "openai/gpt-6", "context_length", 128000);
await matchCatalogReference("catalog-3", "provider/model", "openai/gpt-6");
await createCatalogReference("catalog-4", "custom/my-model", "My Model");
clearAdminToken();
equal(calls[4].url, "./api/catalog");
equal(new Headers(calls[4].init.headers).get("Authorization"), "Bearer test-admin-token");
equal(calls[5].url, "./api/catalog/refresh");
equal(new Headers(calls[5].init.headers).get("If-Match"), "catalog-1");
equal(JSON.parse(calls[5].init.body as string), { sources: ["models.dev"] });
equal(calls[6].url, "./api/catalog/override");
equal(JSON.parse(calls[6].init.body as string), { target: "reference", id: "openai/gpt-6", field: "context_length", value: 128000 });
equal(calls[7].url, "./api/catalog/match");
equal(JSON.parse(calls[7].init.body as string), { accessId: "provider/model", referenceId: "openai/gpt-6" });
equal(calls[8].url, "./api/catalog/reference");
equal(new Headers(calls[8].init.headers).get("If-Match"), "catalog-4");
equal(JSON.parse(calls[8].init.body as string), { id: "custom/my-model", fields: { name: "My Model" } });
equal(parseCatalogValue("reasoning", "false"), false);
equal(parseCatalogValue("input_modalities", '["text","image"]'), ["text", "image"]);
let rejected = false;
try { parseCatalogValue("context_length", ""); } catch { rejected = true; }
equal(rejected, true);
setAdminToken("test-admin-token");
await getSnapshot();
await getSnapshotCsv();
await previewSnapshot('{"format_version":1,"registry":{}}');
await applySnapshot('{"format_version":1,"registry":{}}', "current-snapshot");
clearAdminToken();
equal(calls[9].url, "./api/snapshot");
equal(calls[10].url, "./api/snapshot.csv");
equal(new Headers(calls[10].init.headers).get("Authorization"), "Bearer test-admin-token");
equal(calls[11].url, "./api/snapshot/preview");
equal(calls[11].init.method, "POST");
equal(calls[11].init.body, '{"format_version":1,"registry":{}}');
equal(calls[12].url, "./api/snapshot/apply");
equal(new Headers(calls[12].init.headers).get("If-Match"), "current-snapshot");
equal(calls[12].init.body, calls[11].init.body);
setAdminToken("test-admin-token");
await previewKeyAdoption("native/key", "adopt");
await applyKeyAdoption({ keyId: "native/key", operation: "adopt", revision: "adoption-revision", previewToken: "preview-token", selectedRoutes: [], nativeRoutes: [], blocked: [], canApply: true, nativePermissionsPreserved: true });
clearAdminToken();
equal(calls[13].url, "./api/keys/adopt");
equal(JSON.parse(calls[13].init.body as string), { keyId: "native/key", operation: "adopt", phase: "preview" });
equal(calls[14].url, "./api/keys/adopt");
equal(new Headers(calls[14].init.headers).get("If-Match"), "adoption-revision");
equal(JSON.parse(calls[14].init.body as string), { keyId: "native/key", operation: "adopt", phase: "apply", previewToken: "preview-token" });
setAdminToken("test-admin-token");
await revealKeySecret("native/key");
clearAdminToken();
equal(calls[15].url, "./api/keys/native%2Fkey/secret");
equal(calls[15].init.method, "POST");
equal(new Headers(calls[15].init.headers).get("Authorization"), "Bearer test-admin-token");
equal(calls[15].init.cache, "no-store");
console.log("Live API request contract: OK");
