import { useEffect, useState } from "react";
import { request } from "./api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";

type Row = Record<string, unknown>;
type ReviewContext = { source: string; capturedAt: string; version: string; providers: Row[]; models: Row[]; virtualKeys: Row[]; routingRules: Row[]; errors: unknown[] };
const rows = (value: unknown): Row[] => Array.isArray(value) ? value.filter((row): row is Row => !!row && typeof row === "object" && !Array.isArray(row)) : [];
const text = (value: unknown) => typeof value === "string" || typeof value === "number" ? String(value) : "—";
const format = (value: unknown) => typeof value === "string" ? value : JSON.stringify(value, null, 2);
const aliasEntries = (key: Row) => key.aliases && typeof key.aliases === "object" && !Array.isArray(key.aliases) ? Object.entries(key.aliases as Row) : [];

export default function GatewayInventory({ onModels }: { onModels: () => void }) {
  const [data, setData] = useState<ReviewContext | null>(null);
  const [error, setError] = useState("");
  const [section, setSection] = useState<"providers" | "aliases" | "routing" | "keys">("providers");
  const [search, setSearch] = useState("");
  const load = () => request<ReviewContext>("review-context").then(value => { setData(value); setError(""); }).catch(() => setError("Impossible de lire la copie du gateway."));
  useEffect(() => { void load(); }, []);
  if (error) return <div role="alert" className="space-y-3"><p>{error}</p><Button onClick={() => void load()}>Réessayer</Button></div>;
  if (!data) return <p role="status">Chargement du gateway…</p>;
  const providers = rows(data.providers), keys = rows(data.virtualKeys), rules = rows(data.routingRules);
  const aliases = providers.flatMap(provider => rows(provider.keys).flatMap(key => aliasEntries(key).map(([name, value]) => ({ name, value, provider: text(provider.name), key: text(key.name) }))));
  const unavailableAliases = providers.flatMap(provider => rows(provider.keys)).filter(key => key.aliases_status).length;
  const query = search.trim().toLocaleLowerCase();
  const match = (value: unknown) => !query || JSON.stringify(value).toLocaleLowerCase().includes(query);
  const tabs = [{ id: "providers", name: "Fournisseurs", count: providers.length }, { id: "aliases", name: "Alias et deployments", count: unavailableAliases ? `${aliases.length} lisibles · ${unavailableAliases} à récupérer` : aliases.length }, { id: "routing", name: "Routage", count: rules.length }, { id: "keys", name: "Permissions des clés", count: keys.length }] as const;
  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-semibold">Gateway existant</h2><p className="mt-2 max-w-prose text-sm text-muted-foreground">Configuration Bifrost récupérée depuis {data.source}. Ces éléments existent indépendamment des fiches Registry.</p></div><Button variant="outline" onClick={onModels}>Voir mes modèles</Button></header>
    <div className="flex flex-wrap gap-2" aria-label="Configuration du gateway">{tabs.map(tab => <Button key={tab.id} variant={section === tab.id ? "default" : "outline"} aria-pressed={section === tab.id} onClick={() => { setSection(tab.id); setSearch(""); }}>{tab.name} <span className="ml-1 tabular-nums">{tab.count}</span></Button>)}</div>
    <Input aria-label="Rechercher dans le gateway" placeholder="Rechercher un fournisseur, un modèle ou une clé…" value={search} onChange={event => setSearch(event.target.value)} className="max-w-lg" />
    {data.errors?.length > 0 && <details className="rounded-sm border p-3 text-sm"><summary className="cursor-pointer">Limites de la capture ({data.errors.length})</summary><ul className="mt-3 space-y-2">{data.errors.map((item, index) => <li className="break-words" key={index}>{format(item)}</li>)}</ul></details>}
    {section === "providers" && <div className="grid gap-4 lg:grid-cols-2">{providers.filter(match).map(provider => <Card key={text(provider.name)}><CardHeader><CardTitle className="flex items-center justify-between gap-3">{text(provider.name)}<Badge variant="secondary">Bifrost natif</Badge></CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">{rows(provider.keys).length} clé(s) fournisseur · {rows(data.models).filter(model => model.provider === provider.name).length} références de modèles dans la configuration</p>{rows(provider.keys).map(key => <details key={text(key.id)} className="rounded-sm border p-3"><summary className="cursor-pointer text-sm font-medium">{text(key.name)} <span className="font-normal text-muted-foreground">· poids {text(key.weight)} · {key.enabled === true ? "active" : key.enabled === false ? "désactivée" : "état inconnu"}</span></summary><div className="mt-3 space-y-2 text-xs"><p>Modèles autorisés</p><pre className="whitespace-pre-wrap break-all rounded-sm bg-muted p-2">{format(key.models)}</pre><p>Modèles bloqués</p><pre className="whitespace-pre-wrap break-all rounded-sm bg-muted p-2">{format(key.blacklisted_models)}</pre><p>{key.aliases_status ? "Alias non récupérés (champ chiffré)" : `${aliasEntries(key).length} alias / deployment(s)`}. Les secrets ne sont pas importés.</p></div></details>)}</CardContent></Card>)}</div>}
    {section === "aliases" && <div className="space-y-3">{unavailableAliases > 0 && <p role="status" className="rounded-sm border bg-muted p-3 text-sm">Les alias de {unavailableAliases} clé(s) n’ont pas pu être lus. Leur absence ci-dessous ne signifie pas qu’aucun alias n’existe.</p>}<p className="text-sm text-muted-foreground">Un alias natif associe un nom demandé à une cible sur une clé fournisseur. Sa présence ne définit pas, à elle seule, une répartition entre fournisseurs.</p>{aliases.filter(match).map(alias => <Card key={`${alias.provider}/${alias.key}/${alias.name}`}><CardContent className="space-y-2 pt-5"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="break-all">{alias.name}</strong><Badge variant="secondary">Bifrost natif</Badge></div><p className="text-sm text-muted-foreground">{alias.provider} · {alias.key}</p><pre className="overflow-auto whitespace-pre-wrap break-all rounded-sm bg-muted p-3 text-xs">{format(alias.value)}</pre></CardContent></Card>)}{!aliases.filter(match).length && <p className="text-sm text-muted-foreground">{unavailableAliases ? "Aucun alias lisible dans cette capture." : "Aucun alias ne correspond à cette recherche."}</p>}</div>}
    {section === "routing" && <div className="space-y-3"><p className="text-sm text-muted-foreground">Règles natives conservées telles qu’elles ont été récupérées. Enregistrer une fiche ne remplace pas ces règles.</p>{rules.filter(match).map(rule => <Card key={text(rule.id)}><CardContent className="space-y-3 pt-5"><div className="flex flex-wrap items-center justify-between gap-3"><strong>{text(rule.name)}</strong><Badge variant={rule.enabled === true ? "success" : "secondary"}>{rule.enabled === true ? "Active" : rule.enabled === false ? "Désactivée" : "État inconnu"}</Badge></div><p className="text-sm text-muted-foreground">Priorité {text(rule.priority)} · portée {text(rule.scope)}</p><pre className="overflow-auto whitespace-pre-wrap break-all rounded-sm bg-muted p-3 text-xs">{format(rule.cel_expression ?? rule.query ?? "Condition non disponible")}</pre><div className="space-y-1">{rows(rule.targets).map((target, index) => <p key={index} className="break-all text-sm">{text(target.provider)} / {text(target.model)} <span className="text-muted-foreground">· poids {text(target.weight)}</span></p>)}</div><details className="text-xs text-muted-foreground"><summary className="cursor-pointer">Règle complète et secours</summary><pre className="mt-2 overflow-auto whitespace-pre-wrap break-all">{format(rule)}</pre></details></CardContent></Card>)}</div>}
    {section === "keys" && <div className="space-y-3"><p className="text-sm text-muted-foreground">Permissions Bifrost existantes. Elles restent distinctes des groupes et sélections créés dans Registry.</p>{keys.filter(match).map(key => <details key={text(key.id)} className="rounded-sm border bg-card p-4"><summary className="cursor-pointer font-medium">{text(key.name)} <span className="text-xs font-normal text-muted-foreground">· {key.is_active === true ? "active" : key.is_active === false ? "inactive" : "état inconnu"}</span></summary><p className="mt-3 text-sm">{key.allow_all_providers === true ? "Tous les fournisseurs autorisés" : key.allow_all_providers === false ? "Fournisseurs explicitement autorisés" : "Portée des fournisseurs non récupérée"}</p>{rows(key.provider_configs).map((provider, index) => <div key={index} className="mt-3 rounded-sm bg-muted p-3"><p className="text-sm font-medium">{text(provider.provider)}</p><pre className="mt-2 overflow-auto whitespace-pre-wrap break-all text-xs">{format(provider)}</pre></div>)}</details>)}</div>}
  </div>;
}
