import { fixture, type Model } from "./demo";
import { emptySelection, limitCells, planCells, resolveTargets, selectedSuiteIds, suiteForScenario, suites, updateViewOverride } from "./lab";
import { defaultViewOptions } from "./ViewOptions";
import { selectionCounts, setVisibleSelection } from "./selection";

const assert = (condition: unknown, message = "Assertion failed") => { if (!condition) throw new Error(message); };
assert.equal = (actual: unknown, expected: unknown, message = "Values differ") => assert(Object.is(actual, expected), `${message}: ${actual} !== ${expected}`);

const models: Model[] = structuredClone(fixture.models);
models[0].accesses[0].id = "custom:primary/opaque-access";
const selection = { ...emptySelection(), modelIds: ["gpt-5"], providerIds: ["openai"], groupIds: ["code"], excludedAccessIds: ["custom:primary/opaque-access"] };
const targets = resolveTargets(models, fixture.groups, selection);
assert.equal(targets.filter(target => target.model.id === "gpt-5").length, 1, "union must dedupe model scopes and preserve access exclusions");
assert(!targets.some(target => target.access.id === "custom:primary/opaque-access"), "exclusion must win across all scopes");
assert(targets.some(target => target.model.id === "text-embedding-3-large"), "provider scope should add models beyond selected groups");
const imageInput = planCells(resolveTargets(models, [], { ...emptySelection(), modelIds: ["gpt-5"] }), [suites.find(suite => suite.id === "vision")!]);
assert.equal(imageInput[0].runnable, true, "chat model with image input can be vision-applicable");
const mixed = planCells(resolveTargets(models, [], { ...emptySelection(), modelIds: ["imagen-4", "text-embedding-3-large"] }), suites.filter(suite => ["image", "embedding", "chat"].includes(suite.id)));
assert.equal(mixed.filter(cell => cell.runnable).length, 2);
assert.equal(mixed.filter(cell => !cell.runnable).length, 4);
assert(mixed.filter(cell => !cell.runnable).every(cell => cell.reason.includes("Not applicable")));
const capped = limitCells(mixed, 1);
assert.equal(capped.filter(cell => cell.runnable).length, 1);
assert(capped.some(cell => cell.reason.includes("case ceiling")));
assert.equal(suiteForScenario(fixture.campaigns[2].scenario)?.id, "tools", "seeded inconclusive campaign must remain retryable");
const sizeOverride = updateViewOverride(defaultViewOptions, {}, { ...defaultViewOptions, size: "large" });
assert.equal(Object.keys(sizeOverride).join(), "size", "local view change must not freeze global fields");
const changedBase = { ...defaultViewOptions, description: false };
const view = { ...changedBase, ...sizeOverride };
assert.equal(view.description, false, "untouched field must follow later global settings");
const resetSize = updateViewOverride(changedBase, sizeOverride, { ...view, size: changedBase.size });
assert.equal(Object.keys(resetSize).length, 0, "matching global value clears local override");
const counts = selectionCounts(["a", "b"], ["a", "c", "c"]);
assert.equal(counts.visibleSelected, 1);
assert.equal(counts.visibleTotal, 2, "grouped duplicates must count once");
assert.equal(counts.hiddenSelected, 1);
assert.equal(setVisibleSelection(["a", "b"], ["a", "c"], true).join(), "a,b,c", "select visible must keep hidden choices");
assert.equal(setVisibleSelection(["a", "b"], ["a", "c"], false).join(), "b", "deselect visible must keep hidden choices");
assert.equal(setVisibleSelection(["a"], [], false).join(), "a", "empty visible scope is a no-op");
const customSuiteIds = setVisibleSelection(suites.map(suite => suite.id), ["chat", "stream"], false);
assert.equal(selectedSuiteIds("custom", customSuiteIds).length, suites.length - 2, "custom selection keeps its subset");
assert.equal(selectedSuiteIds("all", customSuiteIds).length, suites.length, "all mode selects every suite");
assert.equal(selectedSuiteIds("custom", customSuiteIds).join(), customSuiteIds.join(), "switching back restores custom subset");
const protocolCells = planCells(resolveTargets(models, [], { ...emptySelection(), modelIds: ["gpt-5", "claude-sonnet-4"] }), suites.filter(suite => ["responses-chat", "messages-chat"].includes(suite.id)));
assert(protocolCells.some(cell => cell.target.access.provider === "openai" && cell.suite.id === "responses-chat" && cell.runnable));
assert(protocolCells.some(cell => cell.target.access.provider === "anthropic" && cell.suite.id === "messages-chat" && cell.runnable));
assert(protocolCells.some(cell => cell.target.access.provider === "azure" && cell.suite.id === "responses-chat" && !cell.runnable));
const unknownTool = planCells(resolveTargets(models, [], { ...emptySelection(), modelIds: ["gpt-5-mini"] }), [suites.find(suite => suite.id === "tools")!])[0];
assert(unknownTool.runnable && unknownTool.reason.includes("unknown, eligible to probe"), "unknown capability should be testable without becoming a support claim");
console.log("Laboratory selection, exclusions, applicability, and case ceiling: OK");
