import { useState } from "react";
import { ArrowRight, Search, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { BrandIcon, displayProvider } from "./BrandIcon";
import { emptyModelFilters, filterModels, type Model, type ModelFilters } from "./demo";
import { defaultViewOptions, ViewControls, type ViewOptions } from "./ViewOptions";

const filterLabels: Record<keyof ModelFilters, string> = { search: "Search", creator: "Creator", provider: "Serving provider", task: "Usage / task", input: "Input", output: "Output", capability: "Capability" };
const unique = (items: string[]) => [...new Set(items)].sort((a, b) => a.localeCompare(b));
const sizeClass = { small: "min-[560px]:grid-cols-2 xl:grid-cols-4", medium: "min-[560px]:grid-cols-2 xl:grid-cols-3", large: "lg:grid-cols-2" };
export type ModelBrowserProps = { models: Model[]; selected?: string[]; onToggle?: (id: string) => void; onOpen?: (model: Model) => void; preferences?: ViewOptions; compact?: boolean; label?: string; tourFirst?: boolean };
export default function ModelBrowser({ models, selected, onToggle, onOpen, preferences = defaultViewOptions, compact = false, label = "Models", tourFirst = false }: ModelBrowserProps) {
  const [filters, setFilters] = useState<ModelFilters>(emptyModelFilters);
  const [groupBy, setGroupBy] = useState("none");
  const [override, setOverride] = useState<Partial<ViewOptions>>({});
  const view = { ...preferences, ...override };
  const setFilter = (field: keyof ModelFilters, value: string) => setFilters(old => ({ ...old, [field]: value }));
  const choices: { field: keyof ModelFilters; items: string[] }[] = [
    { field: "creator", items: unique(models.map(m => m.creator)) },
    { field: "provider", items: unique(models.flatMap(m => m.accesses.map(a => a.provider))) },
    { field: "task", items: unique(models.flatMap(m => m.tasks)) },
    { field: "input", items: unique(models.flatMap(m => m.inputModalities)) },
    { field: "output", items: unique(models.flatMap(m => m.outputModalities)) },
    { field: "capability", items: unique(models.flatMap(m => Object.entries(m.capabilities).filter(([, status]) => status !== "Unknown").map(([name]) => name))) },
  ];
  const filtered = filterModels(models, filters);
  const grouped = new Map<string, Model[]>();
  if (groupBy !== "none") for (const model of filtered) {
    const names = groupBy === "provider" ? unique(model.accesses.map(a => displayProvider(a.provider))) : groupBy === "creator" ? [model.creator] : model.tasks.length ? model.tasks : ["Other"];
    for (const name of names) grouped.set(name, [...(grouped.get(name) || []), model]);
  }
  const sections: [string, Model[]][] = groupBy === "none" ? [["", filtered]] : [...grouped.entries()].sort(([a], [b]) => a.localeCompare(b));
  const hiddenSelectedIds = (selected || []).filter(id => !filtered.some(model => model.id === id));
  const hiddenSelected = hiddenSelectedIds.length;
  const active = (Object.keys(filters) as (keyof ModelFilters)[]).filter(field => filters[field]);
  const renderCard = (model: Model, index: number) => <Card key={model.id} data-tour={tourFirst && index === 0 ? "first-model" : undefined} className={`gap-2 py-0 transition-colors hover:border-primary/40 ${compact ? "" : ""}`}><CardHeader className="border-b py-3"><div className="flex min-w-0 items-start gap-3"><BrandIcon model={model} mode={view.logo} /><div className="min-w-0 flex-1"><CardTitle className="truncate text-sm">{model.name}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{model.creator} · {model.family}</p></div>{onToggle && <Checkbox aria-label={`Select ${model.name}`} checked={selected?.includes(model.id)} onCheckedChange={() => onToggle(model.id)} />}</div></CardHeader><CardContent className="space-y-2 pb-3">
    {view.description && <p className={`text-sm text-muted-foreground ${view.size === "small" ? "line-clamp-1" : "line-clamp-2"}`}>{model.summary}</p>}
    {view.metadata && <div className="flex flex-wrap gap-1">{model.tasks.map(task => <Badge key={task} variant="secondary">{task}</Badge>)}<Badge variant="outline">{model.inputModalities.join(", ")} → {model.outputModalities.join(", ")}</Badge></div>}
    {view.providers && <div className="flex flex-wrap gap-1 text-xs text-muted-foreground">Serving: {model.accesses.map(a => <Badge key={a.id} variant="outline" title={a.id}>{displayProvider(a.provider)}</Badge>)}</div>}
    {view.evidence && <p className="text-xs text-muted-foreground">{Object.values(model.capabilities).filter(status => status === "Observed in simulated campaign").length} simulated observations · {Object.values(model.capabilities).filter(status => status === "Declared").length} declarations</p>}
    {onOpen && <Button variant="outline" size="sm" className="w-full" onClick={() => onOpen(model)}>View details<ArrowRight className="size-3.5" /></Button>}
    {onToggle && <Button variant={selected?.includes(model.id) ? "secondary" : "outline"} size="sm" className="w-full" onClick={() => onToggle(model.id)}>{selected?.includes(model.id) ? "Selected" : "Select model"}</Button>}
  </CardContent></Card>;
  return <div className="space-y-4"><div data-tour={tourFirst ? "filters" : undefined} className="space-y-2"><div className="flex flex-wrap items-center gap-2"><div className="relative min-w-48 flex-1"><Search className="absolute top-2.5 left-3 size-4 text-muted-foreground" /><Input aria-label={`Search ${label.toLowerCase()}`} placeholder="Name, ID, creator, provider or access ID…" value={filters.search} onChange={e => setFilter("search", e.target.value)} className="pl-9" /></div><ViewControls value={view} onChange={next => setOverride(old => { const changed = (Object.keys(next) as (keyof ViewOptions)[]).find(key => next[key] !== view[key]); return changed ? { ...old, [changed]: next[changed] } : old; })} onReset={() => setOverride({})} scope={label} /></div><div className="flex flex-wrap gap-2">{choices.slice(0, 3).map(({ field, items }) => <Select key={field} value={filters[field] || "all"} onValueChange={value => setFilter(field, value === "all" ? "" : value)}><SelectTrigger aria-label={filterLabels[field]} className="w-auto min-w-30 max-w-50 text-xs"><SelectValue placeholder={filterLabels[field]} /></SelectTrigger><SelectContent><SelectItem value="all">{filterLabels[field]}: All</SelectItem>{items.map(item => <SelectItem key={item} value={item}>{field === "provider" ? displayProvider(item) : item}</SelectItem>)}</SelectContent></Select>)}<Select value={groupBy} onValueChange={setGroupBy}><SelectTrigger aria-label="Group models by" className="w-auto min-w-36 text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">No grouping</SelectItem><SelectItem value="creator">Group by creator</SelectItem><SelectItem value="provider">Group by provider</SelectItem><SelectItem value="task">Group by usage</SelectItem></SelectContent></Select><details className="relative text-xs"><summary className="flex h-9 cursor-pointer items-center rounded-sm border px-3">More filters{choices.slice(3).filter(choice => filters[choice.field]).length ? ` (${choices.slice(3).filter(choice => filters[choice.field]).length})` : ""}</summary><div className="absolute right-0 z-20 mt-1 flex w-52 flex-col gap-2 rounded-sm border bg-popover p-2 shadow-md">{choices.slice(3).map(({ field, items }) => <Select key={field} value={filters[field] || "all"} onValueChange={value => setFilter(field, value === "all" ? "" : value)}><SelectTrigger aria-label={filterLabels[field]} className="w-full text-xs"><SelectValue placeholder={filterLabels[field]} /></SelectTrigger><SelectContent><SelectItem value="all">{filterLabels[field]}: All</SelectItem>{items.map(item => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select>)}</div></details></div>
    {active.length > 0 && <div className="flex flex-wrap items-center gap-1 text-xs"><span className="text-muted-foreground">Active:</span>{active.map(field => <Button key={field} size="sm" variant="secondary" className="h-7" onClick={() => setFilter(field, "")}>{filterLabels[field]}: {field === "provider" ? displayProvider(filters[field]) : filters[field]}<X className="size-3" /></Button>)}<Button variant="ghost" size="sm" onClick={() => setFilters(emptyModelFilters)}>Clear all</Button></div>}
  </div>{hiddenSelected > 0 && onToggle && <div className="flex flex-wrap items-center gap-1 text-xs"><span className="text-muted-foreground">Selected outside current results:</span>{hiddenSelectedIds.map(id => <Button key={id} variant="secondary" size="sm" className="h-7" onClick={() => onToggle(id)}>{models.find(model => model.id === id)?.name || id}<X className="size-3" /></Button>)}</div>}<p className="text-xs text-muted-foreground">{filtered.length} of {models.length} models{selected && ` · ${selected.length} selected${hiddenSelected ? ` (${hiddenSelected} hidden by filters)` : ""}`} · grouping is for browsing only; it does not create routing groups.</p>
  {filtered.length ? sections.map(([group, items]) => <section key={group || "all"} className="space-y-2">{group && <h3 className="text-sm font-semibold">{group} <span className="font-normal text-muted-foreground">{items.length}</span></h3>}{view.layout === "grid" ? <div className={`grid gap-3 ${compact ? view.size === "small" ? "sm:grid-cols-2 xl:grid-cols-3" : view.size === "large" ? "grid-cols-1" : "sm:grid-cols-2" : sizeClass[view.size]}`}>{items.map(renderCard)}</div> : <div className="overflow-x-auto rounded-sm border"><Table><TableHeader><TableRow><TableHead>Model</TableHead>{view.metadata && <><TableHead>Creator / series</TableHead><TableHead>Usage / modalities</TableHead></>}{view.providers && <TableHead>Serving providers</TableHead>}{view.evidence && <TableHead>Evidence</TableHead>}<TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{items.map(model => <TableRow key={model.id} data-tour={tourFirst && model.id === filtered[0]?.id ? "first-model" : undefined}><TableCell><div className="flex items-center gap-2"><BrandIcon model={model} mode={view.logo} /><span className="font-medium">{model.name}</span></div>{view.description && <p className="mt-1 max-w-60 truncate text-xs text-muted-foreground">{model.summary}</p>}</TableCell>{view.metadata && <><TableCell>{model.creator} · {model.family}</TableCell><TableCell>{model.tasks.join(", ")}<p className="text-xs text-muted-foreground">{model.inputModalities.join(", ")} → {model.outputModalities.join(", ")}</p></TableCell></>}{view.providers && <TableCell>{model.accesses.map(a => displayProvider(a.provider)).join(", ")}</TableCell>}{view.evidence && <TableCell className="text-xs">{Object.values(model.capabilities).filter(status => status === "Observed in simulated campaign").length} simulated · {Object.values(model.capabilities).filter(status => status === "Declared").length} declared</TableCell>}<TableCell className="text-right">{onToggle ? <Button size="sm" variant="outline" onClick={() => onToggle(model.id)}>{selected?.includes(model.id) ? "Selected" : "Select"}</Button> : onOpen && <Button size="sm" variant="ghost" onClick={() => onOpen(model)}>Details <ArrowRight className="size-3.5" /></Button>}</TableCell></TableRow>)}</TableBody></Table></div>}</section>) : <div className="rounded-sm border border-dashed p-8 text-center"><Search className="mx-auto mb-3 size-8 text-muted-foreground" /><p className="font-medium">No matching models</p><p className="mt-1 text-xs text-muted-foreground">Change a filter or clear all to see the catalogue.</p><Button className="mt-3" variant="outline" onClick={() => setFilters(emptyModelFilters)}>Clear filters</Button></div>}</div>;
}
