import { CapabilityIcon, CapabilityItem, ModelCapabilitiesPanel, ModelCapabilitiesSummary, ModelModalitiesSummary } from '@/components/registry/model-capabilities';
import { ModelCapabilitiesSummary as PreviousTextSummary } from './history/2026-09-27-text-capabilities-summary';
import { fixtureModels } from '@/experiments/key-composer-prototype/state';
import type { GalleryEntry } from './types';
import { VercelCapabilityCandidate, VercelCapabilityPopover } from './VercelCapabilityCandidate';

const model = fixtureModels[0];
const cases = [
  { label: 'Déclarations du modèle', model },
  { label: 'Données inconnues', model: { ...model, capabilities: { Reasoning: 'Unknown' as const, Vision: 'Unknown' as const } } },
  { label: 'Observation simulée', model: { ...model, capabilities: { 'Tool calling': 'Observed in simulated campaign' as const } } },
  { label: 'Aucune donnée', model: { ...model, inputModalities: [], outputModalities: [], capabilities: {} } },
  { label: 'Plusieurs modalités', model: { ...model, inputModalities: ['Text', 'Image', 'Audio', 'Video'], outputModalities: ['Text', 'Image', 'Vector'] } },
];
const fixtureContext = { scope: 'Modèle de référence', source: 'Donnée fictive', execution: 'Non vérifiée' };
const entry = (id: string, title: string, level: GalleryEntry['level'], Component: GalleryEntry['Component']): GalleryEntry => ({ id, title, family: 'Capacités et modalités', level, origin: 'Registry · Lucide + Radix', version: 'À valider', source: 'ui/src/components/registry/model-capabilities.tsx', description: 'Variante actuelle à comparer dans la galerie.', Component });
export const capabilityEntries: GalleryEntry[] = [
  { ...entry('capability-vercel-comparison', 'Panneau · comparaison Vercel', 'Organismes', () => <div className="flex flex-wrap items-start gap-6"><figure className="min-w-0"><figcaption className="mb-2 text-xs text-muted-foreground">Référence fournie</figcaption><div className="relative h-[340px] w-[328px] max-w-full overflow-hidden rounded-md border"><img src="./component-gallery/vercel-capabilities.png" alt="Capture du panneau de capacités Vercel" className="absolute left-[-500px] top-[-135px] max-w-none" width="1001" height="563" /></div></figure><div className="min-w-0"><p className="mb-2 text-xs text-muted-foreground">Présentation retenue · exemple fictif</p><VercelCapabilityCandidate /><div className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><span>Ouverture clavier :</span><VercelCapabilityPopover /></div></div></div>), version: 'Présentation validée · icône {}', source: 'ui/src/dev/component-gallery/VercelCapabilityCandidate.tsx', description: 'Présentation retenue pour le panneau ; fixture visuelle sans données de modèle réel ni correspondance au contrat Registry.' },
  { id: 'capability-text-history', title: 'Historique · résumé texte et icônes', family: 'Capacités et modalités', level: 'Molécules', origin: 'Prototype 27 sept · avant décision', version: 'Historique conservé', source: 'ui/src/dev/component-gallery/history/2026-09-27-text-capabilities-summary.tsx', description: 'Capture exacte de la variante précédente avec libellés visibles dans le résumé.', Component: () => <PreviousTextSummary model={model} /> },
  entry('capability-icons', 'Icônes de capacités et modalités', 'Atomes', () => <div className="flex flex-wrap gap-5">{['Text','Image','Audio','Video','Vector','Chat','Reasoning','Vision','Tool calling','Tools','Streaming','Structured output','Image generation','Embeddings'].map(name => <div key={name} className="flex items-center gap-2 text-sm"><CapabilityIcon name={name}/><span>{name}</span></div>)}</div>),
  entry('capability-items', 'Icône, libellé et état', 'Molécules', () => <div className="flex flex-wrap gap-6"><CapabilityItem name="Reasoning" status="Declared"/><CapabilityItem name="Vision" status="Unknown"/><CapabilityItem name="Tool calling" status="Observed in simulated campaign"/></div>),
  { ...entry('capability-summaries', 'Résumés des capacités · icônes seules', 'Molécules', () => <div className="grid gap-5 sm:grid-cols-2">{cases.map(item => <div key={item.label} className="flex min-w-0 flex-col gap-2"><p className="text-xs font-medium text-muted-foreground">{item.label}</p><ModelCapabilitiesSummary model={item.model} context={fixtureContext}/><ModelCapabilitiesSummary model={item.model} stacked context={fixtureContext}/></div>)}</div>), version: 'Résumé retenu · icônes seules', description: 'Résumé retenu avec +N ; le panneau Vercel complet est partagé avec les cartes.' },
  { ...entry('modality-summaries', 'Résumés des modalités · directions et débordement', 'Molécules', () => <div className="grid gap-5 sm:grid-cols-2">{cases.map(item => <div key={item.label} className="flex min-w-0 flex-col gap-2"><p className="text-xs font-medium text-muted-foreground">{item.label}</p><ModelModalitiesSummary model={item.model}/></div>)}</div>), version: 'A retenu · icônes entrée → sortie', description: 'Résumé partagé retenu, masquable indépendamment des capacités dans les options d’affichage.' },
  { ...entry('capability-panel', 'Panneau groupé · sortie, entrée, fonctions', 'Organismes', () => <div className="grid gap-6 lg:grid-cols-2">{cases.slice(0,4).map(item => <div key={item.label} className="min-w-0 rounded-sm border p-4"><p className="mb-4 text-sm font-semibold">{item.label}</p><ModelCapabilitiesPanel model={item.model} context={fixtureContext}/></div>)}</div>), version: 'Présentation Vercel intégrée', description: 'Panneau partagé complet ; états issus des données de chaque exemple, y compris les valeurs non renseignées.' },
];
