// Exact pre-extraction prototype rendering preserved from the working-tree source read on 27 September 2026.
// Imports, names and gallery wrappers are the only adaptations.
import { AudioLines, BrainCircuit, Code2, Database, Eye, FileText, Image, Sparkles, Video, Wrench } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import type { Capability } from "@/domain/registry";
import { fixtureModels, type ProtoModel } from "@/experiments/key-composer-prototype/state";
import { useCopy, useTerm } from "@/lib/locale";
import type { GalleryEntry } from "./types";

const capabilityIcons: Record<string, typeof BrainCircuit> = { Reasoning: BrainCircuit, Vision: Eye, "Tool calling": Wrench, Tools: Wrench, "Image generation": Image, Embeddings: Sparkles, Streaming: AudioLines, "Structured output": Code2, Chat: Sparkles };
function PreviousCapabilities({ model }: { model: ProtoModel }) {
  const copy = useCopy();
  const term = useTerm();
  const declared = Object.entries(model.capabilities).filter(([, state]) => state === "Declared");
  const unknown = Object.entries(model.capabilities).filter(([, state]) => state === "Unknown");
  return <div className="flex flex-wrap items-center gap-0.5" aria-label={copy("Model-level capabilities", "Capacités du modèle de référence")}>
    {declared.map(([name]) => { const Icon = capabilityIcons[name] || Sparkles; return <Popover key={name}><PopoverTrigger asChild><button type="button" title={copy(`${name}: declared for reference model`, `${term(name)} : déclaré pour le modèle de référence`)} aria-label={copy(`${name}: declared for reference model. Show details`, `${term(name)} : déclaré pour le modèle de référence. Afficher le détail`)} className="inline-flex size-7 items-center justify-center rounded-sm text-foreground/75 hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><Icon className="size-3.5" /></button></PopoverTrigger><PopoverContent className="w-60 p-2 text-xs"><p className="font-semibold">{term(name)}</p><dl className="mt-1 grid grid-cols-[auto_1fr] gap-x-3 gap-y-1"><dt>{copy("Status", "État")}</dt><dd>{copy("Declared", "Déclaré")}</dd><dt>{copy("Scope", "Portée")}</dt><dd>{copy("Reference model", "Modèle de référence")}</dd><dt>{copy("Source", "Source")}</dt><dd>{copy("Synthetic fixture", "Donnée fictive")}</dd><dt>{copy("Provider access", "Accès fournisseur")}</dt><dd>{copy("Not specified", "Non renseigné")}</dd><dt>{copy("Execution", "Exécution")}</dt><dd>{copy("Not tested", "Non testée")}</dd>{name === "Reasoning" && <><dt>{copy("Effort levels", "Niveaux d’effort")}</dt><dd>{copy("Not specified", "Non renseignés")}</dd></>}</dl></PopoverContent></Popover>; })}
    {unknown.length > 0 && <Popover><PopoverTrigger asChild><button type="button" title={copy(`${unknown.length} capabilities not specified`, `${unknown.length} capacité${unknown.length === 1 ? "" : "s"} non renseignée${unknown.length === 1 ? "" : "s"}`)} aria-label={copy(`${unknown.length} capabilities not specified. Show details`, `${unknown.length} capacité${unknown.length === 1 ? "" : "s"} non renseignée${unknown.length === 1 ? "" : "s"}. Afficher le détail`)} className="rounded-sm px-1 text-xs text-muted-foreground hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">+{unknown.length} ?</button></PopoverTrigger><PopoverContent className="w-56 p-2 text-xs"><p className="font-semibold">{copy("Not specified", "Non renseigné")}</p><p>{unknown.map(([name]) => term(name)).join(", ")}</p><p className="mt-1 text-muted-foreground">{copy("No claim of missing support or provider test.", "Cela ne signifie ni absence de prise en charge, ni test fournisseur.")}</p></PopoverContent></Popover>}
  </div>;
}

const modalityIcons: Record<string, typeof FileText> = { Text: FileText, Image, Audio: AudioLines, Video, Vector: Database };
function PreviousModalities({ model, stacked = false }: { model: ProtoModel; stacked?: boolean }) {
  const copy = useCopy();
  const term = useTerm();
  const icons = (items: string[], direction: string) => items.map(name => { const Icon = modalityIcons[name] || FileText; return <span key={name} title={`${term(name)} ${direction}`} className="inline-flex size-5 items-center justify-center"><Icon className="size-4" /></span>; });
  const input = icons(model.inputModalities, copy("input", "en entrée"));
  const output = icons(model.outputModalities, copy("output", "en sortie"));
  const details = <PopoverContent className="w-60 p-2 text-xs"><p className="font-semibold">{copy("Directional modalities", "Modalités par direction")}</p><dl className="mt-1 grid grid-cols-[auto_1fr] gap-x-3 gap-y-1"><dt>{copy("Inputs", "Entrées")}</dt><dd>{model.inputModalities.map(term).join(", ") || copy("Not specified", "Non renseignées")}</dd><dt>{copy("Outputs", "Sorties")}</dt><dd>{model.outputModalities.map(term).join(", ") || copy("Not specified", "Non renseignées")}</dd><dt>{copy("Scope", "Portée")}</dt><dd>{copy("Reference model · synthetic fixture", "Modèle de référence · donnée fictive")}</dd><dt>{copy("Provider access", "Accès fournisseur")}</dt><dd>{copy("Not specified per access", "Non renseigné par accès")}</dd></dl></PopoverContent>;
  const label = copy(`Inputs: ${model.inputModalities.join(", ") || "not specified"}; outputs: ${model.outputModalities.join(", ") || "not specified"}. Show details`, `Entrées : ${model.inputModalities.map(term).join(", ") || "non renseignées"} ; sorties : ${model.outputModalities.map(term).join(", ") || "non renseignées"}. Afficher le détail`);
  return <Popover><PopoverTrigger asChild><button type="button" title={label} aria-label={label} className={`min-h-7 max-w-full rounded-sm text-foreground/75 hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${stacked ? "grid w-full gap-1 px-0.5 text-left" : "inline-flex items-center gap-1 px-1"}`}>{stacked ? <><span className="flex items-center gap-1"><span className="w-14 shrink-0 text-[11px] text-muted-foreground">{copy("Inputs", "Entrées")}</span>{input.length ? input : <span className="text-xs">?</span>}</span><span className="flex items-center gap-1"><span className="w-14 shrink-0 text-[11px] text-muted-foreground">{copy("Outputs", "Sorties")}</span>{output.length ? output : <span className="text-xs">?</span>}</span></> : <><span className="sr-only">{copy("Inputs", "Entrées")}</span>{input.length ? input : <span className="text-xs">?</span>}<span aria-hidden className="px-0.5">→</span><span className="sr-only">{copy("Outputs", "Sorties")}</span>{output.length ? output : <span className="text-xs">?</span>}</>}</button></PopoverTrigger>{details}</Popover>;
}

function PreviousCapabilityTable({ model }: { model: ProtoModel }) {
  const copy = useCopy();
  const term = useTerm();
  const capabilityStatus = (item: Capability) => item === "Declared" ? copy("Declared", "Déclaré") : item === "Observed in simulated campaign" ? copy("Observed in simulated campaign", "Observé dans une campagne simulée") : copy("Unknown", "Inconnu");
  return <div className="overflow-x-auto"><table className="w-full min-w-96 text-left text-sm"><thead><tr className="border-b text-muted-foreground"><th className="py-2 pr-3 font-medium">{copy("Capability", "Capacité")}</th><th className="py-2 pr-3 font-medium">{copy("Model declaration", "Déclaration du modèle")}</th><th className="py-2 pr-3 font-medium">{copy("Source", "Source")}</th><th className="py-2 font-medium">{copy("Access evidence", "Donnée par accès")}</th></tr></thead><tbody>{Object.entries(model.capabilities).map(([label, status]) => <tr key={label} className="border-b last:border-0"><td className="py-2 pr-3">{term(label)}</td><td className="py-2 pr-3"><Badge variant={status === "Declared" ? "success" : status === "Observed in simulated campaign" ? "outline" : "secondary"}>{capabilityStatus(status)}</Badge></td><td className="py-2 pr-3 text-muted-foreground">{copy("Synthetic fixture; individual source not recorded", "Donnée fictive ; source individuelle non enregistrée")}</td><td className="py-2 text-muted-foreground">{status === "Observed in simulated campaign" ? copy("Simulated campaign result", "Résultat de campagne simulée") : copy("Not tested", "Non testé")}</td></tr>)}</tbody></table></div>;
}

const model = fixtureModels[0];
export const previousCapabilityEntries: GalleryEntry[] = [
  { id: "previous-capability-summary", title: "Ancien résumé des capacités", family: "Capacités et modalités", level: "Molécules", origin: "Prototype 27 sept · avant extraction", version: "Avant extraction", source: "ui/src/experiments/key-composer-prototype/cards.tsx · fonction Capabilities (lecture avant modification)", description: "Icônes déclarées, compteur des inconnues et popover individuel avec état, portée et source.", Component: () => <PreviousCapabilities model={model} /> },
  { id: "previous-modalities-inline", title: "Anciennes modalités · ligne", family: "Capacités et modalités", level: "Molécules", origin: "Prototype 27 sept · avant extraction", version: "Avant extraction", source: "ui/src/experiments/key-composer-prototype/cards.tsx · fonction Modalities (lecture avant modification)", description: "Icônes entrée → sortie et popover directionnel.", Component: () => <PreviousModalities model={model} /> },
  { id: "previous-modalities-stacked", title: "Anciennes modalités · empilées", family: "Capacités et modalités", level: "Molécules", origin: "Prototype 27 sept · avant extraction", version: "Avant extraction", source: "ui/src/experiments/key-composer-prototype/cards.tsx · fonction Modalities (lecture avant modification)", description: "Même composant original avec stacked=true, comme sur carte carrée.", Component: () => <PreviousModalities model={model} stacked /> },
  { id: "previous-capability-table", title: "Ancien tableau des propriétés", family: "Capacités et modalités", level: "Organismes", origin: "Prototype 27 sept · avant extraction", version: "Avant extraction", source: "ui/src/experiments/key-composer-prototype/ModelDetail.tsx · onglet Properties (lecture avant modification)", description: "Tableau des capacités, déclarations, source synthétique et preuve par accès.", Component: () => <PreviousCapabilityTable model={model} /> },
];
