import { useState } from "react";
import { Bell, ChevronRight, MoreHorizontal, Plus } from "lucide-react";
import type { GalleryEntry } from "./types";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Toggle } from "@/components/ui/toggle";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel, FieldLegend, FieldSet } from "@/components/ui/field";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Skeleton } from "@/components/ui/skeleton";
import { DottedSeparator, Separator } from "@/components/ui/separator";
import { Table, TableBody, TableCaption, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { DropdownMenu, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdownMenu";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider } from "@/components/ui/sidebar";
import { Tree } from "@/components/ui/treeView";

const Row = ({ label, children }: { label: string; children: React.ReactNode }) => <div className="flex flex-wrap items-center gap-2"><span className="w-28 shrink-0 text-xs text-muted-foreground">{label}</span>{children}</div>;
const Stack = ({ children }: { children: React.ReactNode }) => <div className="flex max-w-full flex-col gap-4">{children}</div>;

function Buttons() {
  const [activated, setActivated] = useState(false);
  const variants = ["default", "secondary", "outline", "ghost", "link", "destructive"] as const;
  return <Stack><Row label="Variantes">{variants.map(variant => <Button key={variant} variant={variant}>{variant}</Button>)}</Row><Row label="Tailles"><Button size="sm">Petit</Button><Button>Taille normale</Button><Button size="lg">Grand</Button><Button size="icon" aria-label="Ajouter"><Plus /></Button></Row><Row label="États"><Button isLoading disabled>Chargement</Button><Button disabled>Indisponible</Button><Button variant="outline" onClick={() => setActivated(!activated)}>{activated ? "Activé" : "Action locale"}</Button></Row></Stack>;
}
function Badges() { return <Stack><Row label="Variantes">{(["default", "secondary", "outline", "success", "warning", "destructive"] as const).map(variant => <Badge key={variant} variant={variant}>{variant}</Badge>)}</Row><Row label="Contexte"><Badge>Publié</Badge><Badge variant="warning">À vérifier</Badge><Badge variant="destructive">Erreur</Badge></Row></Stack>; }
function Inputs() { return <Stack><Row label="Texte"><Input aria-label="Nom" placeholder="Nom du modèle" className="max-w-56" /><Input aria-label="Recherche" type="search" placeholder="Rechercher…" className="max-w-56" /></Row><Row label="États"><Input aria-label="Clé copiable" value="clé-de-démonstration" readOnly showCopyButton className="max-w-64" /><Input aria-label="Champ indisponible" disabled value="Indisponible" className="max-w-48" /></Row></Stack>; }
function Textareas() { return <Stack><Row label="Édition"><Textarea aria-label="Description" placeholder="Décrivez ce modèle…" className="max-w-sm" /></Row><Row label="États"><Textarea aria-label="Description invalide" aria-invalid defaultValue="Valeur à revoir" className="max-w-sm" /><Textarea aria-label="Description indisponible" disabled value="Lecture seule" className="max-w-sm" /></Row></Stack>; }
function Labels() { return <Stack><Row label="Associé"><Label htmlFor="gallery-label-name">Nom du groupe</Label><Input id="gallery-label-name" className="max-w-56" placeholder="Ex. Code" /></Row><Row label="Désactivé"><Label htmlFor="gallery-label-disabled">Champ bloqué</Label><Input id="gallery-label-disabled" disabled className="max-w-56" /></Row></Stack>; }
function Checkboxes() { const [one, setOne] = useState(true); return <Stack><Row label="États"><label className="flex items-center gap-2"><Checkbox checked={one} onCheckedChange={v => setOne(v === true)} />Activé</label><label className="flex items-center gap-2"><Checkbox defaultChecked={false} />À choisir</label><label className="flex items-center gap-2"><Checkbox disabled />Indisponible</label></Row><Row label="Partiel"><Checkbox checked="indeterminate" aria-label="Sélection partielle" /><span className="text-sm">Sélection partielle</span></Row></Stack>; }
function Switches() { const [enabled, setEnabled] = useState(true); return <Stack><Row label="Tailles"><label className="flex items-center gap-2"><Switch size="default" checked={enabled} onCheckedChange={setEnabled} />Normale</label><label className="flex items-center gap-2"><Switch size="md" defaultChecked />Compacte</label></Row><Row label="États"><label className="flex items-center gap-2"><Switch disabled />Indisponible</label><label className="flex items-center gap-2"><Switch defaultChecked />Activé</label></Row></Stack>; }
function Selects() { return <Stack><Row label="Choix"><Select defaultValue="code"><SelectTrigger className="w-52" aria-label="Usage"><SelectValue placeholder="Choisir un usage" /></SelectTrigger><SelectContent><SelectGroup><SelectLabel>Usages</SelectLabel><SelectItem value="code">Code</SelectItem><SelectItem value="chat">Conversation</SelectItem><SelectItem value="image" disabled>Image indisponible</SelectItem></SelectGroup></SelectContent></Select><Select><SelectTrigger className="w-52" aria-label="Fournisseur"><SelectValue placeholder="Choisir un fournisseur" /></SelectTrigger><SelectContent><SelectGroup><SelectLabel>Fournisseurs</SelectLabel><SelectItem value="a">Fournisseur A</SelectItem><SelectItem value="b">Fournisseur B</SelectItem></SelectGroup></SelectContent></Select></Row><Row label="Indisponible"><Select disabled><SelectTrigger className="w-52" aria-label="Sélection indisponible"><SelectValue placeholder="Indisponible" /></SelectTrigger></Select></Row></Stack>; }
function Toggles() { return <Stack><Row label="Variantes"><Toggle aria-label="Activer gras" defaultPressed>Gras</Toggle><Toggle variant="outline" aria-label="Activer italique">Italique</Toggle><Toggle variant="outline" disabled aria-label="Option indisponible">Désactivé</Toggle></Row><Row label="Tailles"><Toggle size="sm" aria-label="Petit">Petit</Toggle><Toggle aria-label="Normal">Normal</Toggle><Toggle size="lg" aria-label="Grand">Grand</Toggle></Row></Stack>; }
function ToggleGroups() { const [layout, setLayout] = useState("grille"); return <Stack><Row label="Exclusif"><ToggleGroup type="single" variant="outline" value={layout} onValueChange={v => v && setLayout(v)} aria-label="Format"><ToggleGroupItem value="grille">Grille</ToggleGroupItem><ToggleGroupItem value="table">Tableau</ToggleGroupItem></ToggleGroup></Row><Row label="Multiple"><ToggleGroup type="multiple" size="sm" aria-label="Filtres"><ToggleGroupItem value="texte">Texte</ToggleGroupItem><ToggleGroupItem value="image">Image</ToggleGroupItem><ToggleGroupItem value="audio">Audio</ToggleGroupItem></ToggleGroup></Row></Stack>; }
function Fields() { return <FieldGroup><FieldSet><FieldLegend>Configuration</FieldLegend><Field orientation="vertical"><FieldLabel htmlFor="gallery-field-name">Nom</FieldLabel><Input id="gallery-field-name" placeholder="Nom du groupe" /><FieldDescription>Visible dans le catalogue.</FieldDescription></Field><Field orientation="horizontal"><Checkbox id="gallery-field-shared" /><FieldLabel htmlFor="gallery-field-shared">Partager ce groupe</FieldLabel></Field><Field data-invalid="true"><FieldLabel htmlFor="gallery-field-error">Identifiant</FieldLabel><Input id="gallery-field-error" aria-invalid defaultValue="?" /><FieldError>Identifiant invalide.</FieldError></Field></FieldSet></FieldGroup>; }
function Cards() { return <div className="grid gap-3 sm:grid-cols-2"><Card><CardHeader><CardTitle>Modèle de référence</CardTitle><CardDescription>Carte complète avec actions.</CardDescription></CardHeader><CardContent><Badge variant="success">Disponible</Badge></CardContent><CardFooter><Button size="sm">Consulter</Button></CardFooter></Card><Card><CardHeader><CardTitle>Accès fournisseur</CardTitle><CardDescription>État compact.</CardDescription></CardHeader><CardContent><p className="text-sm">Deux variantes de composition visibles.</p></CardContent></Card></div>; }
function Alerts() { return <Stack>{(["default", "info", "warning", "destructive"] as const).map(variant => <Alert key={variant} variant={variant}><Bell /><AlertTitle>{({ default: "Information", info: "Info", warning: "Attention", destructive: "Erreur" })[variant]}</AlertTitle><AlertDescription>Message de démonstration pour l’état {variant}.</AlertDescription></Alert>)}</Stack>; }
function Skeletons() { return <Stack><Row label="Texte"><Skeleton className="h-4 w-48" /><Skeleton className="h-4 w-28" /></Row><Row label="Carte"><Skeleton className="size-10 rounded-full" /><div className="flex flex-col gap-2"><Skeleton className="h-4 w-40" /><Skeleton className="h-3 w-28" /></div></Row></Stack>; }
function Separators() { return <Stack><div className="flex flex-col gap-2"><span className="text-sm">Horizontal</span><Separator /></div><div className="flex h-10 items-center gap-3"><span className="text-sm">Avant</span><Separator orientation="vertical" /><span className="text-sm">Après</span></div><div className="flex flex-col gap-2"><span className="text-sm">Pointillé local</span><DottedSeparator /></div></Stack>; }
function Tables() { return <Table><TableCaption>Exemple local de deux accès.</TableCaption><TableHeader><TableRow><TableHead>Modèle</TableHead><TableHead>Fournisseur</TableHead><TableHead>État</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Alpha</TableCell><TableCell>A</TableCell><TableCell><Badge variant="success">Actif</Badge></TableCell></TableRow><TableRow><TableCell>Beta</TableCell><TableCell>B</TableCell><TableCell><Badge variant="warning">À vérifier</Badge></TableCell></TableRow></TableBody></Table>; }
function Tooltips() { return <TooltipProvider><Row label="Survol / focus"><Tooltip><TooltipTrigger asChild><Button variant="outline">Information</Button></TooltipTrigger><TooltipContent>Cette aide apparaît au survol ou au focus.</TooltipContent></Tooltip><Tooltip><TooltipTrigger asChild><Button size="icon" variant="ghost" aria-label="Notifications"><Bell /></Button></TooltipTrigger><TooltipContent side="right">Notifications</TooltipContent></Tooltip></Row></TooltipProvider>; }
function Popovers() { return <Row label="Panneau"><Popover><PopoverTrigger asChild><Button variant="outline">Ouvrir les détails</Button></PopoverTrigger><PopoverContent><h3 className="font-medium">Détails du modèle</h3><p className="text-sm text-muted-foreground">Contenu local dans un popover.</p></PopoverContent></Popover><Popover><PopoverTrigger asChild><Button variant="ghost">Autres options</Button></PopoverTrigger><PopoverContent align="start"><h3 className="font-medium">Options</h3><Checkbox id="gallery-popover-option" /><Label htmlFor="gallery-popover-option">Activer</Label></PopoverContent></Popover></Row>; }
function Dialogs() { return <Row label="Fenêtre"><Dialog><DialogTrigger asChild><Button>Ouvrir la fenêtre</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Modifier le groupe</DialogTitle><DialogDescription>Exemple local, sans sauvegarde.</DialogDescription></DialogHeader><Label htmlFor="gallery-dialog-name">Nom</Label><Input id="gallery-dialog-name" defaultValue="Code" /><DialogFooter><Button>Terminer</Button></DialogFooter></DialogContent></Dialog></Row>; }
function Sheets() { return <Row label="Panneaux">{(["right", "left", "top", "bottom"] as const).map(side => <Sheet key={side}><SheetTrigger asChild><Button variant="outline">{({ right: "Droite", left: "Gauche", top: "Haut", bottom: "Bas" })[side]}</Button></SheetTrigger><SheetContent side={side}><SheetHeader><SheetTitle>Détails du groupe</SheetTitle><SheetDescription>Panneau ouvert depuis {({ right: "la droite", left: "la gauche", top: "le haut", bottom: "le bas" })[side]}.</SheetDescription></SheetHeader><div className="p-4 text-sm">Contenu de démonstration local.</div></SheetContent></Sheet>)}</Row>; }
function Dropdowns() { const [selected, setSelected] = useState("grille"); const [checked, setChecked] = useState(true); return <Row label="Menus"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline"><MoreHorizontal /> Actions</Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuLabel>Affichage</DropdownMenuLabel><DropdownMenuGroup><DropdownMenuItem onSelect={() => {}}>Ouvrir</DropdownMenuItem><DropdownMenuItem disabled>Indisponible</DropdownMenuItem></DropdownMenuGroup><DropdownMenuSeparator /><DropdownMenuCheckboxItem checked={checked} onCheckedChange={setChecked}>Montrer les détails</DropdownMenuCheckboxItem><DropdownMenuRadioGroup value={selected} onValueChange={setSelected}><DropdownMenuRadioItem value="grille">Grille</DropdownMenuRadioItem><DropdownMenuRadioItem value="table">Tableau</DropdownMenuRadioItem></DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu></Row>; }
function Sidebars() { return <SidebarProvider><div className="flex h-64 max-w-full overflow-hidden rounded-sm border"><Sidebar collapsible="none" className="w-56 shrink-0"><SidebarHeader className="font-medium">Navigation</SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>Catalogue</SidebarGroupLabel><SidebarGroupContent><SidebarMenu><SidebarMenuItem><SidebarMenuButton isActive>Modèles</SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton>Groupes</SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton variant="outline" size="sm">Paramètres</SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter className="text-xs">Exemple borné</SidebarFooter></Sidebar><div className="min-w-0 flex-1 p-4 text-sm text-muted-foreground">Canvas de démonstration</div></div></SidebarProvider>; }
const treeData = [{ data: { id: "catalogue", name: "Catalogue" }, children: [{ data: { id: "alpha", name: "Modèle Alpha" } }, { data: { id: "beta", name: "Modèle Beta" } }] }, { data: { id: "groupes", name: "Groupes" }, children: [{ data: { id: "code", name: "Code" } }] }];
function Trees() { return <div className="max-w-sm overflow-hidden rounded-sm border p-2"><Tree data={treeData} fitContainer levelsToExpandByDefault={1} renderItem={({ item, hasChildren, isExpanded, onToggle }) => <button type="button" className="flex w-full items-center gap-2 rounded-sm px-2 py-1 text-left text-sm hover:bg-accent" onClick={onToggle} aria-expanded={hasChildren ? isExpanded : undefined}><ChevronRight className={`size-4 shrink-0 ${isExpanded ? "rotate-90" : ""}`} aria-hidden /><span className="truncate">{item.name}</span></button>} /></div>; }
function ColorTokens() { return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[
  ["Fond", "bg-background text-foreground"], ["Carte", "bg-card text-card-foreground"], ["Popover", "bg-popover text-popover-foreground"],
  ["Primaire", "bg-primary text-primary-foreground"], ["Secondaire", "bg-secondary text-secondary-foreground"], ["Muet", "bg-muted text-muted-foreground"],
  ["Accent", "bg-accent text-accent-foreground"], ["Destructif", "bg-destructive text-white"], ["Bordure", "bg-border text-foreground"],
].map(([name, classes]) => <div key={name} className={`flex min-h-16 items-center rounded-sm border px-3 text-sm ${classes}`}>{name}</div>)}</div>; }
function Typography() { return <Stack><p className="font-sans text-xs">Geist · petit texte · text-xs</p><p className="font-sans text-sm">Geist · texte secondaire · text-sm</p><p className="font-sans text-base">Geist · texte normal · text-base</p><p className="font-sans text-lg font-medium">Geist · sous-titre · text-lg</p><p className="font-sans text-xl font-semibold">Geist · titre · text-xl</p><p className="font-sans text-2xl font-semibold">Geist · grand titre · text-2xl</p><p className="font-mono text-sm">Geist Mono · identifiant modele-001</p></Stack>; }

const origin = "Bifrost / shadcn · Radix";
const adapted = "Bifrost / shadcn adapté · Radix";
const familyFor = (id: string) => {
  if (["button", "toggle", "toggle-group", "dropdownMenu"].includes(id)) return "Actions";
  if (["input", "textarea", "label", "checkbox", "switch", "select", "field"].includes(id)) return "Saisie et sélection";
  if (["badge", "alert", "skeleton", "tooltip"].includes(id)) return "États et feedback";
  if (["dialog", "sheet", "popover"].includes(id)) return "Superpositions";
  if (["sidebar", "treeView"].includes(id)) return "Navigation";
  if (id === "card") return "Cartes";
  if (id === "table") return "Tableaux";
  return "Fondations";
};
const make = (id: string, title: string, level: GalleryEntry["level"], Component: GalleryEntry["Component"], description: string, source = `ui/src/components/ui/${id}.tsx`, provenance = origin): GalleryEntry => ({ id: `primitive-${id}`, title, family: familyFor(id), level, origin: provenance, version: "Version locale actuelle", source, description, Component });
export const primitiveEntries: GalleryEntry[] = [
  { id: "foundation-colors", title: "Couleurs sémantiques", family: "Fondations", level: "Fondations", origin: "Bifrost / tokens locaux", version: "Version locale actuelle", source: "ui/src/globals.css", description: "Tokens de couleur actifs dans les thèmes clair et sombre.", Component: ColorTokens },
  { id: "foundation-typography", title: "Typographie", family: "Fondations", level: "Fondations", origin: "Bifrost / Geist local", version: "Version locale actuelle", source: "ui/src/globals.css", description: "Geist, Geist Mono et tailles réellement utilisées par l’interface.", Component: Typography },
  make("button", "Boutons", "Atomes", Buttons, "Variantes, tailles, chargement et état désactivé."),
  make("badge", "Badges", "Atomes", Badges, "Six variantes sémantiques locales."),
  make("input", "Champs de saisie", "Atomes", Inputs, "Saisie, recherche, copie et indisponibilité."),
  make("textarea", "Zones de texte", "Atomes", Textareas, "Édition et états invalides ou désactivés."),
  make("label", "Libellés", "Atomes", Labels, "Libellés liés aux champs."),
  make("checkbox", "Cases à cocher", "Atomes", Checkboxes, "Cochée, libre, partielle et désactivée."),
  make("switch", "Interrupteurs", "Atomes", Switches, "Deux tailles et états interactifs."),
  make("select", "Sélections", "Molécules", Selects, "Choix groupés, placeholder et option désactivée."),
  make("toggle", "Boutons bascule", "Atomes", Toggles, "Variantes, tailles et état pressé.", undefined, adapted),
  make("toggle-group", "Groupes de bascules", "Molécules", ToggleGroups, "Sélection exclusive ou multiple.", undefined, adapted),
  make("field", "Champs composés", "Molécules", Fields, "Libellé, aide, validation et orientation.", undefined, adapted),
  make("card", "Cartes", "Molécules", Cards, "Composition complète et compacte."),
  make("alert", "Alertes", "Molécules", Alerts, "Quatre niveaux de message."),
  make("skeleton", "Squelettes", "Atomes", Skeletons, "Chargement de texte et de carte."),
  make("separator", "Séparateurs", "Atomes", Separators, "Horizontal, vertical et pointillé."),
  make("table", "Tableaux", "Organismes", Tables, "En-tête, lignes, cellules et légende."),
  make("tooltip", "Infobulles", "Molécules", Tooltips, "Aide au survol et au focus."),
  make("popover", "Panneaux contextuels", "Molécules", Popovers, "Deux panneaux déclenchables."),
  make("dialog", "Fenêtres modales", "Organismes", Dialogs, "Fenêtre accessible avec titre et description."),
  make("sheet", "Panneaux latéraux", "Organismes", Sheets, "Ouverture depuis quatre côtés."),
  make("dropdownMenu", "Menus déroulants", "Molécules", Dropdowns, "Actions, case et choix exclusif."),
  make("sidebar", "Barres latérales", "Organismes", Sidebars, "Navigation locale bornée au canvas."),
  make("treeView", "Arbres", "Organismes", Trees, "Navigation hiérarchique dépliable."),
];
